#ifndef BOARD_CONFIG_BLE_CARBON_CONFIG_H
#define BOARD_CONFIG_BLE_CARBON_CONFIG_H

#define CONFIG_CPU_CORTEX_M_HAS_VTOR 1

// Commented by Aananth (27 Jun 2021) as it is too early to support such feature
// #define CONFIG_ARCH_HAS_RAMFUNC_SUPPORT 1
#define CONFIG_ARM 1
#define CONFIG_ASSEMBLER_ISA_THUMB2 1
#define CONFIG_CPU_CORTEX_M4	1
#if defined (CONFIG_CPU_CORTEX_M4)
  #define CONFIG_CPU_CORTEX_M 	1
#endif

#define CONFIG_MP_NUM_CPUS  1
#define CONFIG_NUM_IRQS			4U
#define CONFIG_ZERO_LATENCY_IRQS	1
#define CONFIG_CPU_CORTEX_M_HAS_BASEPRI	1
#define	CONFIG_CPU_CORTEX_M_HAS_PROGRAMMABLE_FAULT_PRIOS	1
#define CONFIG_ARMV7_M_ARMV8_M_MAINLINE	1

#define CONFIG_ISR_STACK_SIZE 512
#define CONFIG_MAIN_STACK_SIZE 2048
#define MPU_GUARD_ALIGN_AND_SIZE 0


#endif