/*
 * Created on Mon Jan 08 2024 7:02:20 AM
 *
 * The MIT License (MIT)
 * Copyright (c) 2024 Aananth C N
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#include <osek.h>
#include <os_api.h>

#include <sg_counter.h>

#include <zephyr/kernel.h> // for k_cycle_get_32()
#include <zephyr/sys/time_units.h> // for k_cyc_to_us_near32()



// Global Variables
static u32 _OsTickCount;


///////////////////////////////////////////////////////////////////////////////
// Core OS Alarm / Counter Functions
u32 _GetOsTickCnt(void) {
	return _OsTickCount;
}


/*/ 
 Function: _OsHandleTicks
 Description: This is called by bsp_setup_sytimer() up on every basic OS ticks 
 which in-turned is dervived from OS_TICK_DURATION_ns macro generated by OSEK 
 builder & System Generator tools. 
/*/
int _OsHandleTicks(void) {
	_OsTickCount++;
	OsClearActivationsCounts();

#if ENABLE_UPTIME_PRINTS != 0
	OsComputeUpTime();
#endif
	return 0;
}


/*/ 
 Function: OsHandleCounters
 Description: 
/*/

/// @brief This is called by _OsHandleTicks(). This function refreshes all 
///        counters configured within this call and also handle alarms if any alarm
///        expires.
/// @param none 
/// @return 0 if all goes well
int OsHandleCounters(void) {
	static TickType os_ticks_old, k_cyc_us_old;
	TickType os_ticks, k_cyc_us;
	TickType delta;
	int cntr;


	/* Get input from Kernel & OS Counter */
	os_ticks = _GetOsTickCnt();
	k_cyc_us = k_cyc_to_us_near32(k_cycle_get_32());

	/* Increment user configured OSEK Counters */
	for (cntr = 0; cntr < OS_MAX_COUNTERS; cntr++) {
		if (_OsCounterCtrlBlk[cntr].maxallowedvalue < ONE_MSEC_IN_MICROSEC ) {
			delta = (TickType)(k_cyc_us - k_cyc_us_old);
		}
		else {
			delta = (TickType)(os_ticks - os_ticks_old);
		}

		if (delta >= _OsCounterCtrlBlk[cntr].ticksperbase) {
			/* Counter's new count value */
			_OsCounterDataBlk[cntr] += delta;

			/* Check if Alarms can be triggered with the new count value*/
			OsHandleAlarms(cntr, _OsCounterDataBlk[cntr]);

			/* Recalculate next count/tick values */
			os_ticks_old = os_ticks;
			k_cyc_us_old = k_cyc_us;

			/* Counters work like saw-tooth wave, reset if it exceeds the peak */
			if (_OsCounterDataBlk[cntr] > _OsCounterCtrlBlk[cntr].maxallowedvalue) {
				_OsCounterDataBlk[cntr] = 0;
			}
		}
	}

	return 0;
}