#include <ostypes.h>
#include <stdarg.h>
#include <stdio.h>

#include <os_api.h>

#include "versatilepb.h"

/* following line will be generated by OIL file system generator tool */
extern void SystemTickISR(void);

void __attribute__((interrupt)) irq_handler() {
	u32 t0_mis; /* Timer 0 Masked Int. Status Register value */

	/* Timer 0 IRQ Handler */
	if (VIC_IRQSTATUS & (1 << ISR_SN_TIMER01)) {
		/* check if Masked Int. Status for Timer 0 is set */
		t0_mis = *((volatile u32*)(TIMER0_BASE+TIMERMSKINTSTS_OFFSET));
		if (t0_mis) {
			/* acknowledge timer 0 interrupt */
			*((volatile u8*)(TIMER0_BASE+TIMERINTCLR_OFFSET)) = 0;

			/* handle OS Tick */
			SystemTickISR();
		}
	}
}

void __attribute__((interrupt)) undef_handler(void) {
	pr_log("Entered a trap function: %s()\n", __func__);
	for (;;);
}

void __attribute__((interrupt)) swi_handler(void) {
	pr_log("Entered a trap function: %s()\n", __func__);
	for (;;);
}

void __attribute__((interrupt)) prefetch_abort_handler(void) {
	pr_log("Entered a trap function: %s()\n", __func__);
	for (;;);
}

void __attribute__((interrupt)) data_abort_handler(void) {
	pr_log("Entered a trap function: %s()\n", __func__);
	for (;;);
}

void __attribute__((interrupt)) fiq_handler(void) {
	pr_log("Entered a trap function: %s()\n", __func__);
	for (;;);
}

void __copy_vectors(void) {
	extern uint32_t vectors_start;
	extern uint32_t vectors_end;
	uint32_t *vectors_src = &vectors_start;
	uint32_t *vectors_dst = (uint32_t *)0;

	while (vectors_src < &vectors_end)
		*vectors_dst++ = *vectors_src++;
}