#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <time.h>


/* following line will be generated by OIL file system generator tool */
extern void SystemTickISR(void);

timer_t posix_timer;

void systick_handler(int signum) {
	SystemTickISR();
}


int setup_systick(void) {
	struct sigaction action;
	struct itimerspec new_value, old_value;
	sigset_t set;

	memset(&action, 0, sizeof(struct sigaction));
	action.sa_handler = systick_handler;
	if (sigaction(SIGALRM, &action, NULL) == -1)
		perror("sigaction");

	if (timer_create(CLOCK_MONOTONIC, NULL, &posix_timer) == -1)
		perror("timer_create");

	new_value.it_interval.tv_sec = 0;
	new_value.it_interval.tv_nsec = 1000000; /* 1 ms repetition */
	new_value.it_value.tv_sec = 0;
	new_value.it_value.tv_nsec = 1000000; /* 1 ms */

	if (timer_settime(posix_timer, 0, &new_value, &old_value) == -1)
		perror("timer_settime");

	if (sigemptyset(&set) == -1)
		perror("sigemptyset");

	if (sigaddset(&set, SIGRTMIN) == -1)
		perror("sigaddset");

	if (sigprocmask(SIG_BLOCK, &set, NULL) == -1)
		perror("sigprocmask");

	printf("%s() success!\n", __func__);
	return 0;
}